spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/blogspot'
    username: 'docker'
    password: 'docker'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis_db
      port: 6379
